// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyzbvsufolfzmjwwuvlu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5emJ2c3Vmb2xmem1qd3d1dmx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTQzNDUsImV4cCI6MjA3MDEzMDM0NX0.5ztEdVKtUGTlFPLrzyq9pHeC-w1ZN5NDh6h_5KPksqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});